os: Visual Studio 2017
platform: x64

#
# Custom environment variables
#
environment:
  global:
    CYG_ROOT: C:\cygwin_bareflank
    CYG_BASH: C:\cygwin_bareflank\bin\bash
    CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
    CYG_PACKAGES: git,make,gcc-core,gcc-g++,nasm,clang,clang++,cmake,python,gettext
    BFPATH: '%PATH%'
    PATH: '%PATH%;C:\Program Files\NASM'

test: off

#
# Setup Cygwin
#
install:

  #
  # Nasm
  #
  - ps: Start-FileDownload "http://www.nasm.us/pub/nasm/releasebuilds/2.13.03/win64/nasm-2.13.03-installer-x64.exe" -FileName "nasm-installer-x64.exe"
  - nasm-installer-x64.exe /S

  #
  # Cygwin
  #
  - ps: Start-FileDownload "https://cygwin.com/setup-x86_64.exe" -FileName "setup-x86_64.exe"
  - setup-x86_64.exe --quiet-mode --no-shortcuts --only-site --root "%CYG_ROOT%" --site "%CYG_MIRROR%" --local-package-dir "%CYG_ROOT%\var\cache\setup" --packages "%CYG_PACKAGES%"

#
# Build
#
build_script:

  #
  # Visual Studio (MSBuild / Static Libraries)
  #
  - mkdir hypervisor\build
  - cd hypervisor\build
  - cmake -G "Visual Studio 15 2017 Win64" -DEXTENSIONS="C:/projects/extended-apis/CMakeLists.txt" -DENABLE_BUILD_VMM=OFF -DENABLE_BUILD_USERSPACE=OFF -DENABLE_BUILD_TEST=ON ..
  - msbuild /m:3 hypervisor.sln
  - cmake --build . --target eapis_x86_64-test-pe
  - cd ..

  #
  # Cygwin (Shared Libraries)
  #
  - set PATH=%BFPATH%;%APPVEYOR_BUILD_FOLDER%/hypervisor/build_cygwin/bfprefix/bin
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; mkdir hypervisor/build_cygwin"'
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER/hypervisor/build_cygwin; cmake -DEXTENSIONS="../../CMakeLists.txt" -DENABLE_BUILD_TEST=ON .."'
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER/hypervisor/build_cygwin; make -j3"'
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER/hypervisor/build_cygwin; make unittest"'
